### ISSUE TITLE
please tag formal releases

### ISSUE THREAD

**Issue by onlyjob** [peterbourgon/diskv#27]
Please consider assigning version numbers and tagging releases. Tags/releases
are useful for downstream package maintainers (in [Debian](http://debian.org) and other distributions) to export source tarballs, automatically track new releases and to declare dependencies between packages. Read more in the [Debian Upstream Guide](https://wiki.debian.org/UpstreamGuide#Releases_and_Versions).

Versioning provides additional benefits to encourage vendoring of a particular (e.g. latest stable) release contrary to random unreleased snapshots.

Versioning provides safety margin for situations like "ops, we've made a mistake but reverted problematic commit in master". Presumably tagged version/release is better tested/reviewed than random snapshot of "master" branch.

Thank you.

See also

 * http://semver.org/
 * https://en.wikipedia.org/wiki/Software_versioning

**Comment by onlyjob** [comment]
Just closing without resolution or comment??

**Comment by jonboulle** [comment]
FWIW we need this for rkt releases on Debian :-)

**Comment by peterbourgon** [comment]
> Just closing without resolution or comment??

Without a concrete use case, this request represents a change in my process to no perceivable benefit. I'm all on-board with semver conceptually, but in the Go universe there are no tools or practices that leverage it usefully.

> FWIW we need this for rkt releases on Debian :-)

Ah! A concrete use case :)

**Comment by peterbourgon** [comment]
https://github.com/peterbourgon/diskv/releases/tag/v1.0.0

**Comment by onlyjob** [comment]
Thank you, Peter! :)
