### ISSUE TITLE
Still maintained/working?

### ISSUE THREAD

**Issue by rucuriousyet** [peterbourgon/diskv#33]
Just curious as to the status of this project. I like the implementation and things seem to work well. I am working this into a micro file system for a new distributed-decentralized internet project, want to make sure I am not using something that is effectively dead. Thx!

**Comment by peterbourgon** [comment]
Yes, it's still maintained in that I'll fix bugs if you find any. And it's definitely not dead! It's part of the [rkt image storage layer](https://github.com/rkt/rkt/blob/efdf06e201535e5c3f2d1a389ddb0b3e651fcd0d/store/imagestore/store.go#L41), for example.

**Comment by peterbourgon** [comment]
Hopefully that's enough to answer the question :)
