### ISSUE TITLE
ensureCacheSpaceWithLock panics with variable sized keys

### ISSUE THREAD

**Issue by WinstonPrivacy** [peterbourgon/diskv#40]
If variable sized keys are being used, then ensureCacheSpaceWithLock() can panic during the cache cleanup routine which loops through safe(). This occurs if the key being inserted is larger than the last key removed.

It would be better if either this key were inserted anyway (and thus exceeding the cache threshold) or the routine was modified so that it cleared some percent of the total cache size before proceeding.

**Comment by WinstonPrivacy** [comment]
I've fixed or improved a number of things related to this in my fork:

- If ensureCacheSpaceWithLock removes the same key that it adds, the cache size is incorrectly calculated.

- Updating a key with a smaller sized one incorrectly updates the cache size.

- ensureCacheSpaceWithLock now clears out 15% of the cache when it exceeds the limit. Previously, it would clear just enough space to bring it under the limit, and the cache would fill up on the next new key. This causes a lot of CPU thrashing.



-

**Comment by peterbourgon** [comment]
Nice! Would love to see a PR with these fixes (in isolation).

**Comment by akarmarkar** [comment]
Thanks !

**Comment by floren** [comment]
I got bitten by a panic in ensureCacheSpaceWithLock over the weekend, although I'm not clear what I did to trigger it. Any thoughts on building a PR? I look at look at WinstonPrivacy's fork but I'm afraid I can't be sure exactly which commits are relevant to this issue and which are for other things.

**Comment by floren** [comment]
On further review, I'm not convinced that WinstonPrivacy's fixes actually do anything, but I'm also not seeing any way for the cache size to get out of sync.

When Write is called, any existing value is blown out of the cache, with the cache size decremented by whatever was actually in the cache map.

Whenever we read an item and add it to the cache, it increments the cacheSize by whatever the size of the actual value may be.

I don't see a way in which we could, say, push a 100 byte value into the cache but increment the cacheSize by 200.

I've fooled around with tests to try and replicate the crash, but I cannot. I don't know how this happened:

```
panic: 833478 bytes still won't fit in the cache! (max 1048576 bytes)

goroutine 603606 [running]:
github.com/peterbourgon/diskv.(*Diskv).ensureCacheSpaceWithLock(0xc0001413b0,
0xcb7c6, 0x1eb2580, 0xc000d09588)
        github.com/peterbourgon/diskv@v2.0.1+incompatible/diskv.go:611 +0x2bd
github.com/peterbourgon/diskv.(*Diskv).cacheWithLock(0xc0001413b0,
0xc001933b60, 0x26, 0xc0170ae000, 0xcb7c6, 0xf9f82, 0xc000074060,
0x1001)
        github.com/peterbourgon/diskv@v2.0.1+incompatible/diskv.go:532 +0x3f
github.com/peterbourgon/diskv.(*Diskv).cacheWithoutLock(0xc0001413b0,
0xc001933b60, 0x26, 0xc0170ae000, 0xcb7c6, 0xf9f82, 0x0, 0x0)
        github.com/peterbourgon/diskv@v2.0.1+incompatible/diskv.go:550 +0xdc
github.com/peterbourgon/diskv.(*siphon).Read(0xc014d6b170,
0xc0019f0000, 0x1000, 0x1000, 0x778, 0x0, 0x0)
        github.com/peterbourgon/diskv@v2.0.1+incompatible/diskv.go:386 +0x12f
bufio.(*Reader).fill(0xc01cf6eea0)
        bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadSlice(0xc01cf6eea0, 0x30000000000a, 0x158, 0x160,
0xc01474d080, 0x0, 0x0)
        bufio/bufio.go:359 +0x3d
encoding/csv.(*Reader).readLine(0xc000d09c38, 0x16, 0x8, 0xc01474d080,
0xc01458db00, 0x203000)
        encoding/csv/reader.go:218 +0x49
encoding/csv.(*Reader).readRecord(0xc000d09c38, 0x0, 0x0, 0x0, 0x1,
0xc01fecce18, 0x4, 0xc01fecce22, 0x7)
```

This was running on v2.0.1 but I don't see any substantive changes between then and HEAD in terms of the cache.
