### ISSUE TITLE
Suggestion: Improve performance by maintaining structs

### ISSUE THREAD

**Issue by WinstonPrivacy** [peterbourgon/diskv#43]
Currently diskv maintains in-memory values in []byte format. It would be excellent from a performance standpoint if arbitrary structs could be maintained instead as this would eliminate the overhead of deserialization. I suspect that the performance improvement would be 1-2 orders of magnitude depending on the application.

**Comment by peterbourgon** [comment]
I'm not sure how this makes sense. All structures need to eventually get serialized to []byte to make it to disk, there's no avoiding it. By using []byte we allow the user to use whatever serialization makes sense in their use case.

**Comment by WinstonPrivacy** [comment]
The key is that they _eventually_ get serialized to disk. If you are reading and updating the key several hundred times a second or have decoupled the memory and disk (as we've done in our fork), this eliminates a lot of overhead.

**Comment by peterbourgon** [comment]
On second thought that second interface might work. The degenerate case would be

```go
type SerializableBytes []byte

func (b SerializableBytes) Size() int64 {
    return len(b)
}

func (b SerializableBytes) MarshalBinary() ([]byte, error) {
    return b, nil
}
```

**Comment by peterbourgon** [comment]
Could you make your custom structs able to report their serialized size?

**Comment by WinstonPrivacy** [comment]
Hmmm... I'm not totally sure I'm following you (my fault, not yours). But I'm using GOB encoding, so I think the only way to figure out their size would be to serialize them, which defeats the point.

**Comment by peterbourgon** [comment]
We need to know size to be able to abide by CacheSizeMax requirement. I'm not aware of a way to get size of a struct without using unsafe.
