### ISSUE TITLE
"Adding Caching"

### ISSUE THREAD

**Issue by DannyZB** [peterbourgon/diskv#46]
An in-memory caching layer is provided by combining the BasicStore functionality with a simple map structure, and keeping it up-to-date as appropriate. Since the map structure in Go is not threadsafe, it's combined with a RWMutex to provide safe concurrent access.

__________

It is unclear from that statement if that is activated by default,
and if it isn't,
how is this to be implemented?

**Comment by peterbourgon** [comment]
Yes, it is there by default.
