### ISSUE TITLE
[Question] Performance of writes

### ISSUE THREAD

**Issue by wild-endeavor** [peterbourgon/diskv#54]
We use diskv in one of the services I help maintain at work.  Attached is a screenshot of the write performance (in seconds) across a few instances.  Have you ever seen this kind of behavior before?
<img width="1622" alt="Screen Shot 2019-05-30 at 8 53 08 AM" src="https://user-images.githubusercontent.com/2896568/58645854-01aa2800-82b9-11e9-89ac-ec514f893ffc.png">

Most of the time, the writes are extremely fast, but every once in a while, the write time blows up.

Please close the issue is this is not the right place, just not sure where else to post.

**Comment by peterbourgon** [comment]
I dunno! How do you have your Diskv configured? What hardware does it run on? Absent more context this looks suspiciously like i/o throttling or noisy neighbor behavior on a [tiny] cloud instance, but I don't want to assume.

**Comment by wild-endeavor** [comment]
Sorry for the delay - we're running these on c5.2xlarge's.  Let me investigate our configuration and report back later as well.
