### ISSUE TITLE
FUSE? would diskv work?

### ISSUE THREAD

**Issue by xt0fer** [peterbourgon/diskv#55]
Could diskv be used on a [upspin](https://upspin.io/) backend? any thoughts? 

Would it work on upspin's [FUSE filesystem](https://godoc.org/upspin.io/cmd/upspinfs) interface? 
Or would it have to be ported to the upspin [Client](https://godoc.org/upspin.io/client) & [upspin.io/client/file](https://godoc.org/upspin.io/client/file) package?

TIA,
-K

**Comment by peterbourgon** [comment]
Unlikely in all cases.
