### ISSUE TITLE
http file stream

### ISSUE THREAD

**Issue by idefixcert** [peterbourgon/diskv#56]
Hi all,

I just wanna ask how you would serve a file saved in diskv via http. 
I have seen the http.ServeContent, but this needs an io.ReadSeeker.
For http.ServeContent, we need the file.
would you do a io.Copy?

Regards Chris

**Comment by peterbourgon** [comment]
Yes, I'd probably io.Copy from the io.Reader returned by diskv to the http.ResponseWriter, unless you had more specific requirements.
