### ISSUE TITLE
Cannot install using go modules

### ISSUE THREAD

**Issue by paskal** [peterbourgon/diskv#57]
v2.0.1 is the last tagged version that doesn’t include a `go.mod` file

The newer has a go.mod file but is invalid since the module needs to have a `/v3` suffix then.

golang/go#31944 and blang/semver#63 are examples of same issue.

**Comment by peterbourgon** [comment]
The module does have a /v3 suffix. Why is it invalid?

**Comment by paskal** [comment]
Thanks for prompt response and my apologies, this indeed work as expected. I will need to find the dependency which breaks things me.
