### ISSUE TITLE
how large can the db be?

### ISSUE THREAD

**Issue by hiqsociety** [peterbourgon/diskv#74]
if i want to access a key from a db, does it read the whole file into mem or just that particular key section? just wondering if i need to have lots of mem available for this. 100GB per db size advisable etc?

**Comment by peterbourgon** [comment]
In diskv, each key is one-to-one with a file on disk. A diskv "database" is just a directory, potentially including subdirectories, and all the files contained therein. So it can be as big as your disk, I guess. Diskv doesn't really add much meaningful overhead in this dimension.
