### ISSUE TITLE
Question about many tiny files vs block size

### ISSUE THREAD

**Issue by xeoncross** [peterbourgon/diskv#75]
This design creates a single file for every entry. If there are a lot of small entries, this wastes disk space as the default block size is often 4096 bytes or more. I was curious to know if there would be a way to combine the tiny writes into a single index and only break them out into their own files when they grew big enough (user input here?) to effectively be spread out over the file system.

**Comment by peterbourgon** [comment]
Nope! The notion that a diskv entry is 1-to-1 with a file on disk is a core property of the system.
