### ISSUE TITLE
can we append files by DiskV

### ISSUE THREAD

**Issue by pegasas** [peterbourgon/diskv#77]
I have a request to persist buffer into local using diskv.
I wants to add a `AppendStream` method into https://github.com/peterbourgon/diskv/blob/master/diskv.go#L175

Why can't we add such a method before?
Is there any thinking?

**Comment by peterbourgon** [comment]
diskv so far doesn't treat values as "appendable", and while I guess it could be possible to write an AppendStream method, I don't think it's needed to solve the (linked, Kubernetes) problem that you're apparently trying to solve.
